require("items.widgets.weather")
require("items.widgets.display_toggle")
require("items.widgets.notifications")
require("items.widgets.timew")
require("items.widgets.battery")
require("items.widgets.uptime")
require("items.widgets.vpn")
require("items.widgets.volume")
-- require("items.widgets.wifi") -- Disabled: network_load provider uses significant energy
require("items.widgets.cpu")
