require("items.widgets.timew")
require("items.widgets.notifications")
require("items.widgets.uptime")
require("items.widgets.vpn")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.display_toggle")
-- require("items.widgets.wifi")
-- require("items.widgets.cpu")
